name: battery_info
description: Flutter plugin providing detailed information about the device battery (level, health, charging status, etc.). Now supports both IOS and android
version: 1.1.2
homepage: https://github.com/igrik12/battery_info.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.igrik12.battery_info
        pluginClass: BatteryInfoPlugin
      ios:
        pluginClass: BatteryInfoPlugin
